name: music_assistant
description: Dart client for using working with the Music Assistant Websocket API from Dart and Flutter applications
version: 0.1.0
homepage: https://github.com/loopj/music-assistant-dart

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  async: ^2.0.0
  http: ^1.0.0
  json_annotation: ^4.7.0
  logging: ^1.0.0
  uuid: ^4.0.0
  web_socket_channel: ^3.0.0

dev_dependencies:
  build_runner: ^2.0.0
  json_serializable: ^6.0.0
  lints: ^6.0.0